import type { Metadata } from "next";
import { Geist, Geist_Mono, Be_Vietnam_Pro } from "next/font/google";
import MobileMenu from "./components/mobileMenu";
import Image from "next/image";
import Link from "next/link";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const beVietnamPro = Be_Vietnam_Pro({
  variable: "--font-be-vietnam-pro",
  subsets: ["latin"],
  weight: ["400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Iswarayana",
  description: "Generated by create next app",
  icons: {
    icon: "/logo-baru.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className="scroll-smooth overflow-x-hidden">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="sticky top-0 z-50">
        <header className="w-full">
                <nav className="flex bg-zinc-900 items-center justify-between max-w-7xl mx-auto h-20 px-4 sm:px-6 lg:px-8">
                  <div className="flex items-center gap-12">
                    <Link href="/">
                      <Image src="/logo-baru.png" alt="Iswarayana Logo" width={64} height={64} className="h-16 w-auto" />
                    </Link>
        
                    <div className="hidden lg:flex items-center gap-8">
                      <Link href="/models" className="text-cyan-400 text-lg font-medium hover:font-bold transition-all">Models</Link>
                      <Link href="/gallery" className="text-cyan-400 text-lg font-medium hover:font-bold transition-all">Gallery</Link>
                      <Link href="/achievements" className="text-cyan-400 text-lg font-medium hover:font-bold transition-all">Achievements</Link>
                      <Link href="/contact" className="text-cyan-400 text-lg font-medium hover:font-bold transition-all">Contact</Link>
                      <Link href="/product" className="text-cyan-400 text-lg font-medium hover:font-bold transition-all">Store</Link>
                    </div>
                  </div>

                  <div className="hidden lg:flex">
                    <div className="w-72 h-8 rounded-2xl border-2 border-cyan-400 relative flex items-center">
                      <input 
                        type="text" 
                        placeholder="Search..." 
                        className="bg-transparent w-full h-full rounded-2xl pl-4 pr-10 text-white outline-none" 
                      />
                      <div className="absolute right-2">
                        <svg xmlns="http://www.w3.org/2000/svg" width={20} height={20} viewBox="0 0 24 24"><path fill="#20BCED" d="M9.5 16q-2.725 0-4.612-1.888T3 9.5t1.888-4.612T9.5 3t4.613 1.888T16 9.5q0 1.1-.35 2.075T14.7 13.3l5.6 5.6q.275.275.275.7t-.275.7t-.7.275t-.7-.275l-5.6-5.6q-.75.6-1.725.95T9.5 16m0-2q1.875 0 3.188-1.312T14 9.5t-1.312-3.187T9.5 5T6.313 6.313T5 9.5t1.313 3.188T9.5 14"></path></svg>
                      </div>
                    </div>
                  </div>
                  
                  <div className="lg:hidden ">
                    <MobileMenu /> 
                  </div>
                </nav>
              </header>
              </div>
        {children}
        <footer className="bg-zinc-900 p-8 py-16 text-gray-400">
          <div className="max-w-7xl mx-auto grid md:grid-cols-3 gap-8">
            <div>
              <Image src="/logo-baru.png" alt="Iswarayana Logo" width={120} height={120} className="right-20" />
            </div>
            <div>
              <h4 className="font-bold text-white mb-4">Contact Us</h4>
              <p className="text-sm">Department of Automotive and Vehicle Design, Institut Teknologi Sepuluh Nopember, East Java</p>
              <p className="text-sm mt-2">+62 8121214132415 - Fuad</p>
            </div>
            <div>
              <h4 className="font-bold text-white mb-4">Join Our Journey</h4>
              <div className="flex gap-4">
                <Link href="#" className="text-cyan-400 hover:text-cyan-300"><svg xmlns="http://www.w3.org/2000/svg" width={32} height={32} viewBox="0 0 24 24"><path fill="#20BCED" d="M7.8 2h8.4C19.4 2 22 4.6 22 7.8v8.4a5.8 5.8 0 0 1-5.8 5.8H7.8C4.6 22 2 19.4 2 16.2V7.8A5.8 5.8 0 0 1 7.8 2m-.2 2A3.6 3.6 0 0 0 4 7.6v8.8C4 18.39 5.61 20 7.6 20h8.8a3.6 3.6 0 0 0 3.6-3.6V7.6C20 5.61 18.39 4 16.4 4zm9.65 1.5a1.25 1.25 0 0 1 1.25 1.25A1.25 1.25 0 0 1 17.25 8A1.25 1.25 0 0 1 16 6.75a1.25 1.25 0 0 1 1.25-1.25M12 7a5 5 0 0 1 5 5a5 5 0 0 1-5 5a5 5 0 0 1-5-5a5 5 0 0 1 5-5m0 2a3 3 0 0 0-3 3a3 3 0 0 0 3 3a3 3 0 0 0 3-3a3 3 0 0 0-3-3"></path></svg></Link>
                <Link href="#" className="text-cyan-400 hover:text-cyan-300"><svg xmlns="http://www.w3.org/2000/svg" width={32} height={32} viewBox="0 0 24 24"><path fill="#20BCED" d="M22 12c0-5.52-4.48-10-10-10S2 6.48 2 12c0 4.84 3.44 8.87 8 9.8V15H8v-3h2V9.5C10 7.57 11.57 6 13.5 6H16v3h-2c-.55 0-1 .45-1 1v2h3v3h-3v6.95c5.05-.5 9-4.76 9-9.95"></path></svg></Link>
                <Link href="#" className="text-cyan-400 hover:text-cyan-300"><svg xmlns="http://www.w3.org/2000/svg" width={32} height={32} viewBox="0 0 24 24"><path fill="#20BCED" d="M19 3a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2zm-.5 15.5v-5.3a3.26 3.26 0 0 0-3.26-3.26c-.85 0-1.84.52-2.32 1.3v-1.11h-2.79v8.37h2.79v-4.93c0-.77.62-1.4 1.39-1.4a1.4 1.4 0 0 1 1.4 1.4v4.93zM6.88 8.56a1.68 1.68 0 0 0 1.68-1.68c0-.93-.75-1.69-1.68-1.69a1.69 1.69 0 0 0-1.69 1.69c0 .93.76 1.68 1.69 1.68m1.39 9.94v-8.37H5.5v8.37z"></path></svg></Link>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
